# Generated by Django 5.2.6 on 2025-09-26 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_category_blog_category_subcategory_blog_subcategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'SubCategory', 'verbose_name_plural': 'SubCategories'},
        ),
    ]
