# Generated by Django 5.2.6 on 2025-09-27 07:27

import home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_banner_alter_contact_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Websetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=300)),
                ('facebook', models.CharField(max_length=300)),
                ('linkedin', models.CharField(max_length=300)),
                ('instagram', models.CharField(max_length=300)),
                ('twitter', models.CharField(max_length=300)),
                ('google_map', models.CharField(max_length=300)),
                ('short_descriptions', models.CharField(max_length=300)),
                ('meta_title', models.CharField(max_length=300)),
                ('meta_description', models.CharField(max_length=300)),
                ('meta_image', models.ImageField(blank=True, null=True, upload_to=home.models.GenerateAttachmentFilePath())),
                ('logo', models.ImageField(blank=True, null=True, upload_to=home.models.GenerateAttachmentFilePath())),
                ('fav_image', models.ImageField(blank=True, null=True, upload_to=home.models.GenerateAttachmentFilePath())),
                ('google_analytics_id', models.CharField(blank=True, help_text='Enter Google Analytics Tracking ID, e.g., G-XXXXXXXXXX', max_length=20, null=True)),
            ],
        ),
    ]
