# Generated by Django 5.2.6 on 2025-09-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_websetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websetting',
            name='google_map',
            field=models.TextField(blank=True, help_text='Paste your Google Maps iframe embed code here', null=True),
        ),
    ]
