# Generated by Django 5.2.6 on 2025-09-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_websetting_google_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websetting',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='websetting',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='websetting',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='websetting',
            name='fav_image',
            field=models.ImageField(blank=True, null=True, upload_to='favicon/'),
        ),
        migrations.AlterField(
            model_name='websetting',
            name='google_analytics_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='websetting',
            name='google_map',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='websetting',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='websetting',
            name='linkedin',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='websetting',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
        migrations.AlterField(
            model_name='websetting',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='websetting',
            name='meta_image',
            field=models.ImageField(blank=True, null=True, upload_to='meta/'),
        ),
        migrations.AlterField(
            model_name='websetting',
            name='meta_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='websetting',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='websetting',
            name='short_descriptions',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='websetting',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
    ]
