# Generated by Django 5.2.6 on 2025-09-27 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_websetting_address_alter_websetting_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websetting',
            name='smtp_host',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='websetting',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='websetting',
            name='smtp_port',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='websetting',
            name='smtp_use_tls',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='websetting',
            name='smtp_user',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
