# Generated by Django 5.2.6 on 2025-09-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_websetting_smtp_host_websetting_smtp_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='websetting',
            name='smtp_use_ssl',
            field=models.BooleanField(default=False),
        ),
    ]
